# Main Navigation Menu (German)

[[main]]
  name = "Blog"
  pageRef = "blog"
  weight = 10

[[main]]
  name = "Glossar"
  pageRef = "glossary"
  weight = 20

[[main]]
  name = "Autoren"
  pageRef = "authors"
  weight = 30

[[main]]
  name = "Ãœber uns"
  pageRef = "pages/about"
  weight = 40

[[main]]
  name = "Suche"
  pageRef = "search"
  weight = 50

# Footer menu
[[footer]]
  name = "Datenschutz"
  pageRef = "pages/privacy"
  weight = 10

[[footer]]
  name = "Impressum"
  pageRef = "pages/imprint"
  weight = 20

[[footer]]
  name = "Kontakt"
  pageRef = "pages/contact"
  weight = 30
